"""init

Revision ID: 9f288ce4f96f
Revises: 
Create Date: 2026-07-02 05:54:50.848055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f288ce4f96f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('anaemia', sa.Integer(), nullable=True),
    sa.Column('creatinine_phosphokinase', sa.Integer(), nullable=True),
    sa.Column('diabetes', sa.Integer(), nullable=True),
    sa.Column('ejection_fraction', sa.Integer(), nullable=True),
    sa.Column('high_blood_pressure', sa.Integer(), nullable=True),
    sa.Column('platelets', sa.Float(), nullable=True),
    sa.Column('serum_creatinine', sa.Float(), nullable=True),
    sa.Column('serum_sodium', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('smoking', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('DEATH_EVENT', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.String(), nullable=True),
    sa.Column('prediction_result', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('patients')
    # ### end Alembic commands ###
